version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: discordclonepostgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  progresDB:
